#!/usr/bin/perl

use strict;
use warnings;

use File::Basename qw();
$ENV{'LINTIAN_ROOT'} = File::Basename::dirname($0);

do '/usr/bin/lintian-info';

# Local Variables:
# indent-tabs-mode: nil
# End:
# vim: syntax=perl sw=4 sts=4 sr et
