#!/usr/bin/perl

use strict;
use warnings;

use Cwd qw();
use File::Basename qw();

my $lintian4python_root = Cwd::abs_path(File::Basename::dirname($0));

unshift @ARGV, '--profile', '{VENDOR}/python';
unshift @ARGV, '--include-dir', $lintian4python_root if defined $lintian4python_root;
my $command = '/usr/bin/lintian-info';
exec { $command } $command, @ARGV or die;

# Local Variables:
# indent-tabs-mode: nil
# End:
# vim: syntax=perl sw=4 sts=4 sr et
