#!/usr/bin/perl

use strict;
use warnings;

use File::Basename qw();
$ENV{'LINTIAN_ROOT'} = File::Basename::dirname($0);

unshift @INC, "$ENV{'LINTIAN_ROOT'}/lib";
require Lintian::Output;

use Monkey::Patch qw();

my $monkey = Monkey::Patch::patch_package 'Lintian::Output' => '_print' => sub {
    my ($original, $self, $stream, $lead, @args) = @_;
    if ($lead =~ /^([A-Z])(: .*)$/) {
        $lead = "\L$1\E$2";
    }
    return $original->($self, $stream, $lead, @args);
};

do '/usr/bin/lintian';

# Local Variables:
# indent-tabs-mode: nil
# End:
# vim: syntax=perl sw=4 sts=4 sr et
