#!/usr/bin/perl

use strict;
use warnings;

use Cwd qw();
use File::Basename qw();
$ENV{'LINTIAN_ROOT'} = Cwd::abs_path(File::Basename::dirname($0));

do '/usr/bin/lintian-info';
if ($@) {
    die $@;
}

# Local Variables:
# indent-tabs-mode: nil
# End:
# vim: syntax=perl sw=4 sts=4 sr et
