Profile: debian/python
Enable-Tags-From-Check:
 python/bytecompilation,
 python/code-analysis,
 python/depends,
 python/documentation,
 python/egg-info,
 python/extensions,
 python/helpers,
 python/imports,
 python/multi-arch,
 python/package-name,
 python/pth,
 python/pyflakes,
 python/scripts,
 python/teams,
 python/watch,
